  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 176527102129.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t 176527102129.dkr.ecr.us-east-1.amazonaws.com/hello_docker_example:latest .
      - docker tag 176527102129.dkr.ecr.us-east-1.amazonaws.com/hello_docker_example:latest 176527102129.dkr.ecr.us-east-1.amazonaws.com/176527102129.dkr.ecr.us-east-1.amazonaws.com/hello_docker_example:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 176527102129.dkr.ecr.us-east-1.amazonaws.com/176527102129.dkr.ecr.us-east-1.amazonaws.com/hello_docker_example:latest
